const songsData = [
  [
    {
      id: 1,
      song: 'Johnny B. Goode',
      artist: 'Chuck Berry',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Chuck_Berry_1957.jpg/800px-Chuck_Berry_1957.jpg',
      path: './assets/Chuck_Berry_Johnny_B_Goode.mp3',
    },
    {
      id: 2,
      song: 'Jailhouse Rock',
      artist: 'Elvis Presley',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Elvis_Presley_promoting_Jailhouse_Rock.jpg',
      path: './assets/Elvis_Presley_Jailhouse_Rock.mp3',
    },
    {
      id: 3,
      song: 'What\'d I Say',
      artist: 'Ray Charles',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Ray_Charles_classic_piano_pose.jpg',
      path: './assets/Ray_Charles_What\'d_I_Say.mp3',
    },
    {
      id: 4,
      song: 'Whole Lot of Shakin\' Going On',
      artist: 'Jerry Lee Lewis',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Jerry_Lee_Lewis_1950s_publicity_photo_cropped_retouched.jpg',
      path: './assets/Jerry_Lee_Lewis_Whole_Lot_Of_Shakin\'_Going_On.mp3',
    },
    {
      id: 5,
      song: 'Summertime Blues',
      artist: 'Eddie Cochran',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Eddie_Cochran.jpg',
      path: './assets/Eddie_Cochran_Summertime_Blues.mp3',
    },
    {
      id: 6,
      song: 'Lawdy Miss Clawdy',
      artist: 'Lloyd Price',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Publicity_photo_of_Lloyd_Price_-_ht24wk00x_files_046435e7-3a2b-42be-b859-88a492e9b836_%28cropped%29.jpg',
      path: './assets/Lloyd_Price_Lawdy_Miss_Clawdy.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Light My Fire',
      artist: 'The Doors',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/en/9/98/TheDoorsTheDoorsalbumcover.jpg',
      path: './assets/The_Doors_Light_My_Fire.mp3',
    },
    {
      id: 2,
      song: '(I Can\'t Get No) Satisfaction',
      artist: 'Rolling Stones',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/en/7/7f/Satisfaction-us.jpg',
      path: './assets/The_Rolling_Stones_(I_Can\'t_Get_No)_Satisfaction.mp3',
    },
    {
      id: 3,
      song: 'Purple Haze',
      artist: 'Jimi Hendrix',
      description: '',
      image: 'https://www.castlerock.ru/upload/medialibrary/d43/d43027437204542a51db378dc36f7b7f.jpg',
      path: './assets/Jimi_Hendrix_Purple_Haze.mp3',
    },
    {
      id: 4,
      song: 'Whole Lotta Love',
      artist: 'Led Zeppelin',
      description: '',
      image: 'https://lastfm.freetls.fastly.net/i/u/770x0/31ba4e5450b869d226bfabee25cda087.jpg#31ba4e5450b869d226bfabee25cda087',
      path: './assets/Led_Zeppelin_Whole_Lotta_Love.mp3',
    },
    {
      id: 5,
      song: 'I Want To Hold Your Hand',
      artist: 'The Beatles',
      description: '',
      image: 'https://cdnn21.img.ria.ru/images/15010/18/150101870_0:139:600:479_600x0_80_0_0_e34e6f610f59685d3b51f79887075077.jpg.webp',
      path: './assets/The_Beatles_I_Want_To_Hold_Your_Hand.mp3',
    },
    {
      id: 6,
      song: 'Sunshine Of Your Love',
      artist: 'Cream',
      description: '',
      image: 'https://www.kursivom.ru/wp-content/uploads/2017/01/cream_00.jpg',
      path: './assets/Cream_Sunshine_Of_Your_Love.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Bohemian Rhapsody',
      artist: 'Queen',
      description: '',
      image: 'https://nacion.ru/assets/i/ai/4/7/2/i/3237339.jpg',
      path: './assets/Queen_Bohemian_Rhapsody.mp3',
    },
    {
      id: 2,
      song: 'Baba O\'Riley',
      artist: 'The Who',
      description: '',
      image: 'https://i.discogs.com/rtoLAe4zJiVgzjWIi4orK23-WN15N2YpJxeWjUwEIus/rs:fit/g:sm/q:90/h:545/w:555/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTE5Njc2/Ni0xNjM5ODYyMDk0/LTI2OTMuanBlZw.jpeg',
      path: './assets/The_Who_Baba_O_Riley.mp3',
    },
    {
      id: 3,
      song: 'Paranoid',
      artist: 'Black Sabbath',
      description: '',
      image: 'https://i.scdn.co/image/2af99dc3c8acbbe00d913526229def80e7f42e5f',
      path: './assets/Black_Sabbath_Paranoid.mp3',
    },
    {
      id: 4,
      song: 'Comfortably Numb',
      artist: 'Pink Floyd',
      description: '',
      image: 'https://vinyloteka.ru/sites/default/files/styles/1600x/public/field/image/unnamed.jpg?itok=bGPUtM_-&v=1613558692',
      path: './assets/Pink_Floyd_Comfortably_Numb.mp3',
    },
    {
      id: 5,
      song: 'Free Bird',
      artist: 'Lynyrd Skynyrd',
      description: '',
      image: 'https://cdns-images.dzcdn.net/images/artist/d5dfdbe7783133afa602a591bbe6c4e3/500x500.jpg',
      path: './assets/Lynyrd_Skynyrd_Free_Bird.mp3',
    },
    {
      id: 6,
      song: 'Dream On',
      artist: 'Aerosmith',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Aerosmith_1.jpg',
      path: './assets/Aerosmith_Dream_On.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Sweet Child O\' Mine',
      artist: 'Guns N\' Roses',
      description: '',
      image: 'https://www.nashe.ru/storage/29215/conversions/guns-n-roses-large.jpg',
      path: './assets/Guns_N\'_Roses_Sweet_Child_O\'_Mine.mp3',
    },
    {
      id: 2,
      song: 'You Shook Me All Night Long',
      artist: 'AC/DC',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/ru/thumb/8/8b/AC-DC_-_Highway_to_Hell.jpg/220px-AC-DC_-_Highway_to_Hell.jpg',
      path: './assets/AC_DC_You_Shook_Me_All_Night_Long.mp3',
    },
    {
      id: 3,
      song: 'Pour Some Sugar On Me',
      artist: 'Def Leppard',
      description: '',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1704946/da6e369c-83a7-4e93-8683-5ce6ad437e78/1920x',
      path: './assets/Def_Leppard_Pour_Some_Sugar_On_Me.mp3',
    },
    {
      id: 4,
      song: 'Jump',
      artist: 'Van Halen',
      description: '',
      image: 'https://www.seymourduncan.ru/upload/iblock/5aa/g9doxaqr21lbfb4c00fy4cd744id9oz3/Kartinka_1.jpg',
      path: './assets/Van_Halen_Jump.mp3',
    },
    {
      id: 5,
      song: 'I Still Haven\'t Found What I\'m Looking For',
      artist: 'U2',
      description: '',
      image: 'https://cdns-images.dzcdn.net/images/artist/edc3ee765289d41a98fde2fafa78f0fa/500x500.jpg',
      path: './assets/U2_I_Still_Haven\'t_Found_What_I\'m_Looking_For.mp3',
    },
    {
      id: 6,
      song: 'Purple Rain',
      artist: 'Prince',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Prince_at_Coachella_%28cropped%29.jpg/250px-Prince_at_Coachella_%28cropped%29.jpg',
      path: './assets/Prince_&_The_Revolution_Purple_Rain.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Creep',
      artist: 'Radiohead',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/ru/7/72/Radiohead_creep.jpg',
      path: './assets/Radiohead_Creep.mp3',
    },
    {
      id: 2,
      song: 'Enter Sandman',
      artist: 'Metallica',
      description: '',
      image: 'https://rg.ru/uploads/images/2022/08/11/gettyimages-1092751282_2d4.jpeg',
      path: './assets/Metallica_Enter_Sandman.mp3',
    },
    {
      id: 3,
      song: 'Tears In Heaven',
      artist: 'Eric Clapton',
      description: '',
      image: 'https://upload.wikimedia.org/wikipedia/ru/5/5e/Tears_in_heaven.jpg',
      path: './assets/Eric_Clapton_Tears_in_Heaven.mp3',
    },
    {
      id: 4,
      song: 'Californication',
      artist: 'Red Hot Chili Peppers',
      description: '',
      image: 'https://lastfm.freetls.fastly.net/i/u/770x0/df8ead32bf4a4d87bc2f9afbbef7d40c.jpg',
      path: './assets/Red_Hot_Chili_Peppers_Californication.mp3',
    },
    {
      id: 5,
      song: 'Come As You Are',
      artist: 'Nirvana',
      description: '',
      image: 'https://avatars.yandex.net/get-music-content/5496390/06f54371.p.9262/m1000x1000',
      path: './assets/Nirvana_Come_As_You_Are.mp3',
    },
    {
      id: 6,
      song: 'Wind of Change',
      artist: 'Scorpions',
      description: '',
      image: 'https://images.spletnik.ru/i/O/OGnRpcHRxZ/744.jpg',
      path: './assets/Scorpions_Wind_of_Change.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Uprising',
      artist: 'Muse',
      description: '',
      image: 'https://i.guim.co.uk/img/media/7a514f7a62cf504f16775a9ca409dcecfb8237d6/0_26_5574_3344/master/5574.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=b1c4ab5bfc256ed4cc59d9b7c89c7b16',
      path: './assets/Muse_Uprising.mp3',
    },
    {
      id: 2,
      song: 'Toxicity',
      artist: 'System of a Down',
      description: '',
      image: '',
      path: './assets/System_Of_A_Down_Toxicity.mp3',
    },
    {
      id: 3,
      song: 'Burn It to the Ground',
      artist: 'Nickelback',
      description: '',
      image: 'https://lastfm.freetls.fastly.net/i/u/500x500/fa228868f27a4c51b87d28d8c3e83283.jpg',
      path: './assets/Nickelback_Burn_It_to_the_Ground.mp3',
    },
    {
      id: 4,
      song: 'Kryptonite',
      artist: '3 Doors Down',
      description: '',
      image: 'https://i0.wp.com/www.songwritingmagazine.co.uk/wp-content/uploads/3-doors-down-1-by-dove-shore.jpg',
      path: './assets/3_Doors_Down_Kryptonite.mp3',
    },
    {
      id: 5,
      song: 'My Sacrifice',
      artist: 'Creed',
      description: '',
      image: 'https://i.scdn.co/image/ab67616d0000b273a32f2ae4dade83e0d7a294f4',
      path: './assets/Creed_My_Sacrifice.mp3',
    },
    {
      id: 6,
      song: 'Lifeline',
      artist: 'Papa Roach',
      description: '',
      image: 'https://i.iheart.com/v3/catalog/artist/7772?ops=fit(720%2C720)',
      path: './assets/Papa_Roach_Lifeline.mp3',
    },
  ],
];

export default songsData;
