const songsData = [
  [
    {
      id: 1,
      song: 'Johnny B. Goode',
      artist: 'Chuck Berry',
      description: 'Guitarist, singer, and songwriter Charles Edward Anderson “Chuck” Berry was considered a pioneer of rock and roll and a major influence on 20th century popular music. His songs such as “Johnny B. Goode” and “Roll Over Beethoven” are rock and roll standards.',
      image: './assets/Chuck_Berry.jpg',
      path: './assets/Chuck_Berry_Johnny_B_Goode.mp3',
    },
    {
      id: 2,
      song: 'Jailhouse Rock',
      artist: 'Elvis Presley',
      description: 'Elvis Presley, (born Jan. 8, 1935, Tupelo, Miss., U.S.—died Aug. 16, 1977, Memphis, Tenn.), U.S. popular singer, the “King of Rock and Roll.” Presley was raised in Memphis, where he sang Pentecostal church music and listened to black bluesmen and Grand Ole Opry broadcasts.',
      image: './assets/Elvis_Presley.jpg',
      path: './assets/Elvis_Presley_Jailhouse_Rock.mp3',
    },
    {
      id: 3,
      song: 'What\'d I Say',
      artist: 'Ray Charles',
      description: 'Ray Charles was a pianist and vocalist whose style spanned the genres of blues, country, rock & roll, jazz, and soul. Blind at the age of seven, he went on to become a gifted musician, recording such hits as \'Georgia on My Mind\' and \' Hit the Road Jack\'.',
      image: './assets/Ray_Charles.jpg',
      path: './assets/Ray_Charles_What\'d_I_Say.mp3',
    },
    {
      id: 4,
      song: 'Whole Lot of Shakin\' Going On',
      artist: 'Jerry Lee Lewis',
      description: 'Jerry Lee Lewis (September 29, 1935 – October 28, 2022) was an American singer, songwriter and pianist. Nicknamed "The Killer", he was described as "rock & roll\'s first great wild man".',
      image: './assets/Jerry_Lee_Lewis.jpg',
      path: './assets/Jerry_Lee_Lewis_Whole_Lot_Of_Shakin\'_Going_On.mp3',
    },
    {
      id: 5,
      song: 'Summertime Blues',
      artist: 'Eddie Cochran',
      description: 'Ray Edward Cochran (/ˈkɒkrən/; October 3, 1938 – April 17, 1960) was an American rock and roll musician.',
      image: './assets/Eddie_Cochran.jpg',
      path: './assets/Eddie_Cochran_Summertime_Blues.mp3',
    },
    {
      id: 6,
      song: 'Lawdy Miss Clawdy',
      artist: 'Lloyd Price',
      description: 'Lloyd Price (March 9, 1933 – May 3, 2021) was an American singer-songwriter, record executive and bandleader, known as "Mr. Personality", after his 1959 million-selling hit, "Personality". His first recording, "Lawdy Miss Clawdy", was a hit for Specialty Records in 1952.',
      image: './assets/Lloyd_Price.jpg',
      path: './assets/Lloyd_Price_Lawdy_Miss_Clawdy.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Light My Fire',
      artist: 'The Doors',
      description: 'The Doors were an American rock band formed in Los Angeles in 1965, with vocalist Jim Morrison, keyboardist Ray Manzarek, guitarist Robby Krieger, and drummer John Densmore. They were among the most controversial and influential rock acts of the 1960s, partly due to Morrison\'s lyrics and voice, along with his erratic stage persona. The group is widely regarded as an important figure of the era\'s counterculture.',
      image: 'https://upload.wikimedia.org/wikipedia/en/9/98/TheDoorsTheDoorsalbumcover.jpg',
      path: './assets/The_Doors_Light_My_Fire.mp3',
    },
    {
      id: 2,
      song: '(I Can\'t Get No) Satisfaction',
      artist: 'Rolling Stones',
      description: 'The Rolling Stones are a British rock group, formed in 1962, that drew on Chicago blues stylings to create a unique vision of the dark side of post-1960s counterculture. The original members were Mick Jagger, Keith Richards, Brian Jones, Bill Wyman, and Charlie Watts.',
      image: 'https://upload.wikimedia.org/wikipedia/en/7/7f/Satisfaction-us.jpg',
      path: './assets/The_Rolling_Stones_(I_Can\'t_Get_No)_Satisfaction.mp3',
    },
    {
      id: 3,
      song: 'Purple Haze',
      artist: 'Jimi Hendrix',
      description: 'Jimi Hendrix, byname of James Marshall Hendrix, originally John Allen Hendrix, (born November 27, 1942, Seattle, Washington, U.S.—died September 18, 1970, London, England), American rock guitarist, singer, and composer who fused American traditions of blues, jazz, rock, and soul with techniques of British avant-garde rock to redefine the electric guitar in his own image.',
      image: 'https://www.castlerock.ru/upload/medialibrary/d43/d43027437204542a51db378dc36f7b7f.jpg',
      path: './assets/Jimi_Hendrix_Purple_Haze.mp3',
    },
    {
      id: 4,
      song: 'Whole Lotta Love',
      artist: 'Led Zeppelin',
      description: 'Led Zeppelin was a highly innovative band that created a new sound, which has come to be known as heavy metal or hard rock by combining three elements; acoustic folk, hippie mysticism, and power chords with high volume and distortion. They have earned their place as one of the best rock bands in rock history.',
      image: 'https://lastfm.freetls.fastly.net/i/u/770x0/31ba4e5450b869d226bfabee25cda087.jpg#31ba4e5450b869d226bfabee25cda087',
      path: './assets/Led_Zeppelin_Whole_Lotta_Love.mp3',
    },
    {
      id: 5,
      song: 'I Want To Hold Your Hand',
      artist: 'The Beatles',
      description: 'The Beatles were an English rock-pop band, started in Liverpool, England in 1960. The members were John Lennon, Paul McCartney, George Harrison, and Ringo Starr. Most people say they are the most successful and influential band in the history of popular music.',
      image: 'https://cdnn21.img.ria.ru/images/15010/18/150101870_0:139:600:479_600x0_80_0_0_e34e6f610f59685d3b51f79887075077.jpg.webp',
      path: './assets/The_Beatles_I_Want_To_Hold_Your_Hand.mp3',
    },
    {
      id: 6,
      song: 'Sunshine Of Your Love',
      artist: 'Cream',
      description: 'Cream were a British rock band formed in London in 1966. The group consisted of bassist Jack Bruce, guitarist Eric Clapton, and drummer Ginger Baker. Bruce was the primary songwriter and vocalist, although Clapton and Baker also sang and contributed songs. Formed from members of previously successful bands, they are widely regarded as the world\'s first supergroup. Cream were highly regarded for the instrumental proficiency of each of their members.',
      image: 'https://www.kursivom.ru/wp-content/uploads/2017/01/cream_00.jpg',
      path: './assets/Cream_Sunshine_Of_Your_Love.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Bohemian Rhapsody',
      artist: 'Queen',
      description: 'Queen are a British rock band formed in London in 1970. The band comprised Freddie Mercury (lead vocals, piano), Brian May (guitar, vocals), Roger Taylor (drums, vocals) and John Deacon (bass). Their earliest works were influenced by progressive rock, hard rock and heavy metal, but the band gradually ventured into more conventional and radio-friendly works by incorporating further styles, such as arena rock and pop rock.',
      image: 'https://nacion.ru/assets/i/ai/4/7/2/i/3237339.jpg',
      path: './assets/Queen_Bohemian_Rhapsody.mp3',
    },
    {
      id: 2,
      song: 'Baba O\'Riley',
      artist: 'The Who',
      description: 'The Who, British rock group that was among the most popular and influential bands of the 1960s and ’70s and that originated the rock opera. Though primarily inspired by American rhythm and blues, the Who took a bold step toward defining a uniquely British rock vernacular in the 1960s. Shunning the Beatles’ idealized romance and the Rolling Stones’ cocky swagger, the Who rejected pretension and straightforwardly dealt with teenage travails. At a time when rock music was uniting young people all over the world, the Who were friendless, bitter outsiders.',
      image: 'https://i.discogs.com/rtoLAe4zJiVgzjWIi4orK23-WN15N2YpJxeWjUwEIus/rs:fit/g:sm/q:90/h:545/w:555/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTE5Njc2/Ni0xNjM5ODYyMDk0/LTI2OTMuanBlZw.jpeg',
      path: './assets/The_Who_Baba_O_Riley.mp3',
    },
    {
      id: 3,
      song: 'Paranoid',
      artist: 'Black Sabbath',
      description: 'Black Sabbath were an English rock band formed in Birmingham in 1968 by guitarist Tony Iommi, drummer Bill Ward, bassist Geezer Butler and vocalist Ozzy Osbourne. They are often cited as pioneers of heavy metal music.',
      image: 'https://i.scdn.co/image/2af99dc3c8acbbe00d913526229def80e7f42e5f',
      path: './assets/Black_Sabbath_Paranoid.mp3',
    },
    {
      id: 4,
      song: 'Comfortably Numb',
      artist: 'Pink Floyd',
      description: 'Pink Floyd are an English rock band formed in London in 1965. Gaining an early following as one of the first British psychedelic groups, they were distinguished by their extended compositions, sonic experimentation, philosophical lyrics and elaborate live shows.',
      image: 'https://vinyloteka.ru/sites/default/files/styles/1600x/public/field/image/unnamed.jpg?itok=bGPUtM_-&v=1613558692',
      path: './assets/Pink_Floyd_Comfortably_Numb.mp3',
    },
    {
      id: 5,
      song: 'Free Bird',
      artist: 'Lynyrd Skynyrd',
      description: 'Lynyrd Skynyrd , American rock band that rose to prominence during the Southern rock boom of the 1970s on the strength of its triple-guitar attack and gritty working-class attitude. In 2004, Rolling Stone magazine ranked Lynyrd Skynyrd No. 95 on their list of the "100 Greatest Artists of All Time"',
      image: 'https://cdns-images.dzcdn.net/images/artist/d5dfdbe7783133afa602a591bbe6c4e3/500x500.jpg',
      path: './assets/Lynyrd_Skynyrd_Free_Bird.mp3',
    },
    {
      id: 6,
      song: 'Dream On',
      artist: 'Aerosmith',
      description: 'Aerosmith is an American rock band formed in Boston in 1970. The group consists of Steven Tyler (lead vocals), Joe Perry (guitar), Tom Hamilton (bass), Joey Kramer (drums) and Brad Whitford (guitar). They were one of the most popular hard rock bands of the \'70s, setting the style and sound of hard rock and heavy metal for the next two decades with their raunchy, bluesy swagger.',
      image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Aerosmith_1.jpg',
      path: './assets/Aerosmith_Dream_On.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Sweet Child O\' Mine',
      artist: 'Guns N\' Roses',
      description: 'Guns N\' Roses is an American hard rock band from Los Angeles, California, formed in 1985. The lineup, when first signed to Geffen Records in 1986, consisted of vocalist Axl Rose, lead guitarist Slash, rhythm guitarist Izzy Stradlin, bassist Duff McKagan, and drummer Steven Adler. The rise of “grunge” bands like Nirvana and alternative rock effectively put an end to that scene in the early 1990s, but the first blow was struck by one of their own: Guns N’ Roses, the band that made its big popular breakthrough on July 23, 1988, when their first hit single, “Sweet Child O’ Mine” entered the Billboard Top 40',
      image: 'https://www.nashe.ru/storage/29215/conversions/guns-n-roses-large.jpg',
      path: './assets/Guns_N\'_Roses_Sweet_Child_O\'_Mine.mp3',
    },
    {
      id: 2,
      song: 'You Shook Me All Night Long',
      artist: 'AC/DC',
      description: 'AC/DC (stylised as ACϟDC) are an Australian rock band formed in Sydney, New South Wales, Australia in 1973 by Scottish-born brothers Malcolm and Angus Young. Their music has been variously described as hard rock, blues rock, and heavy metal, but the band calls it simply "rock and roll".',
      image: 'https://upload.wikimedia.org/wikipedia/ru/thumb/8/8b/AC-DC_-_Highway_to_Hell.jpg/220px-AC-DC_-_Highway_to_Hell.jpg',
      path: './assets/AC_DC_You_Shook_Me_All_Night_Long.mp3',
    },
    {
      id: 3,
      song: 'Pour Some Sugar On Me',
      artist: 'Def Leppard',
      description: 'Def Leppard are an English rock band formed in 1976 in Sheffield. Since 1992, the band has consisted of Rick Savage (bass, backing vocals), Joe Elliott (lead vocals), Rick Allen (drums, backing vocals), Phil Collen (guitar, backing vocals), and Vivian Campbell (guitar, backing vocals). They established themselves as part of the new wave of British heavy metal movement of the early 1980s.',
      image: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1704946/da6e369c-83a7-4e93-8683-5ce6ad437e78/1920x',
      path: './assets/Def_Leppard_Pour_Some_Sugar_On_Me.mp3',
    },
    {
      id: 4,
      song: 'Jump',
      artist: 'Van Halen',
      description: 'Van Halen (/væn ˈheɪlɛn/ van HAY-len) was an American rock band formed in Pasadena, California, in 1972. Credited with "restoring hard rock to the forefront of the music scene", Van Halen was known for its energetic live shows and for the virtuosity of its lead guitarist, Eddie Van Halen. The band was inducted into the Rock and Roll Hall of Fame in 2007.',
      image: 'https://www.seymourduncan.ru/upload/iblock/5aa/g9doxaqr21lbfb4c00fy4cd744id9oz3/Kartinka_1.jpg',
      path: './assets/Van_Halen_Jump.mp3',
    },
    {
      id: 5,
      song: 'I Still Haven\'t Found What I\'m Looking For',
      artist: 'U2',
      description: 'U2 are an Irish rock band from Dublin, formed in 1976. The group consists of Bono (lead vocals and rhythm guitar), the Edge (lead guitar, keyboards, and backing vocals), Adam Clayton (bass guitar), and Larry Mullen Jr. (drums and percussion). Initially rooted in post-punk, U2\'s musical style has evolved throughout their career, yet has maintained an anthemic quality built on Bono\'s expressive vocals and the Edge\'s chiming, effects-based guitar sounds. Bono\'s lyrics, often embellished with spiritual imagery, focus on personal and sociopolitical themes.',
      image: 'https://cdns-images.dzcdn.net/images/artist/edc3ee765289d41a98fde2fafa78f0fa/500x500.jpg',
      path: './assets/U2_I_Still_Haven\'t_Found_What_I\'m_Looking_For.mp3',
    },
    {
      id: 6,
      song: 'Purple Rain',
      artist: 'Prince',
      description: 'Prince Rogers Nelson (June 7, 1958 – April 21, 2016), more commonly known mononymously as Prince, was an American singer-songwriter, musician, and record producer. The recipient of numerous awards and nominations, he is widely regarded as one of the greatest musicians of his generation. He was known for his flamboyant, androgynous persona; his wide vocal range, which included a far-reaching falsetto and high-pitched screams; and his skill as a multi-instrumentalist, often preferring to play all or most of the instruments on his recordings',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Prince_at_Coachella_%28cropped%29.jpg/250px-Prince_at_Coachella_%28cropped%29.jpg',
      path: './assets/Prince_&_The_Revolution_Purple_Rain.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Creep',
      artist: 'Radiohead',
      description: 'Radiohead, British rock group that was arguably the most accomplished art-rock band of the early 21st century. This revered quintet made some of the most majestic—if most angst-saturated—music of the postmodern era.',
      image: 'https://upload.wikimedia.org/wikipedia/ru/7/72/Radiohead_creep.jpg',
      path: './assets/Radiohead_Creep.mp3',
    },
    {
      id: 2,
      song: 'Enter Sandman',
      artist: 'Metallica',
      description: 'Metallica is an American heavy metal band. The band was formed in 1981 in Los Angeles by vocalist/guitarist James Hetfield and drummer Lars Ulrich and has been based in San Francisco for most of its career. The band\'s fast tempos, instrumentals and aggressive musicianship made them one of the founding "big four" bands of thrash metal, alongside Megadeth, Anthrax and Slayer.',
      image: 'https://rg.ru/uploads/images/2022/08/11/gettyimages-1092751282_2d4.jpeg',
      path: './assets/Metallica_Enter_Sandman.mp3',
    },
    {
      id: 3,
      song: 'Tears In Heaven',
      artist: 'Eric Clapton',
      description: 'Eric Patrick Clapton CBE (born 30 March 1945) is an English rock and blues guitarist, singer, and songwriter. He is regarded as one of the most successful and influential guitarists in rock music.',
      image: 'https://upload.wikimedia.org/wikipedia/ru/5/5e/Tears_in_heaven.jpg',
      path: './assets/Eric_Clapton_Tears_in_Heaven.mp3',
    },
    {
      id: 4,
      song: 'Californication',
      artist: 'Red Hot Chili Peppers',
      description: 'Red Hot Chili Peppers are an American rock band formed in Los Angeles in 1983, comprising vocalist Anthony Kiedis, bassist Flea, drummer Chad Smith, and guitarist John Frusciante. Their music incorporates elements of alternative rock, funk, punk rock, hard rock, hip hop, and psychedelic rock.',
      image: 'https://lastfm.freetls.fastly.net/i/u/770x0/df8ead32bf4a4d87bc2f9afbbef7d40c.jpg',
      path: './assets/Red_Hot_Chili_Peppers_Californication.mp3',
    },
    {
      id: 5,
      song: 'Come As You Are',
      artist: 'Nirvana',
      description: 'Nirvana, American alternative rock group whose breakthrough album, Nevermind (1991), announced a new musical style (grunge) and gave voice to the post-baby boom young adults known as Generation X.  Founded by lead singer and guitarist Kurt Cobain and bassist Krist Novoselic.',
      image: 'https://avatars.yandex.net/get-music-content/5496390/06f54371.p.9262/m1000x1000',
      path: './assets/Nirvana_Come_As_You_Are.mp3',
    },
    {
      id: 6,
      song: 'Wind of Change',
      artist: 'Scorpions',
      description: 'Scorpions are a German rock band formed in 1965 in Hanover by Rudolf Schenker. Since the band\'s inception, its musical style has ranged from hard rock, heavy metal and glam metal to soft rock.',
      image: 'https://images.spletnik.ru/i/O/OGnRpcHRxZ/744.jpg',
      path: './assets/Scorpions_Wind_of_Change.mp3',
    },
  ],
  [
    {
      id: 1,
      song: 'Uprising',
      artist: 'Muse',
      description: 'Muse is an alternative rock band from Teignmouth, England, United Kingdom. The band consists of Matthew Bellamy on lead vocals, piano, keyboard and guitar, Chris Wolstenholme on backing vocals and bass guitar, and Dominic Howard on drums and percussion. Their sound is a blend of alternative rock, classical music, electronica, metal, spanish guitars, and progressive rock.',
      image: 'https://i.guim.co.uk/img/media/7a514f7a62cf504f16775a9ca409dcecfb8237d6/0_26_5574_3344/master/5574.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=b1c4ab5bfc256ed4cc59d9b7c89c7b16',
      path: './assets/Muse_Uprising.mp3',
    },
    {
      id: 2,
      song: 'Toxicity',
      artist: 'System of a Down',
      description: 'System of a Down (also known as SoaD or simply System) is an Armenian American heavy metal band formed in Glendale, California, in 1994. Fusing rock, punk, metal, rap, and even ethnic folk and jazz, and tackling subjects ranging from cultural and political issues to poetry and humor, System of a Down proved themselves true contenders on the rap-metal scene with their sophomore album, Toxicity. Released in September of 2001.',
      image: 'https://www.rollingstone.com/wp-content/uploads/2018/06/system-of-a-down-66260748-b2c4-458f-a349-f83f947a6f67.jpg',
      path: './assets/System_Of_A_Down_Toxicity.mp3',
    },
    {
      id: 3,
      song: 'Burn It to the Ground',
      artist: 'Nickelback',
      description: 'Nickelback is a Canadian rock band formed in 1995 in Hanna, Alberta. It is composed of guitarist and lead vocalist Chad Kroeger, guitarist, keyboardist and backing vocalist Ryan Peake, bassist Mike Kroeger, and drummer Daniel Adair. Their incredible songwriting ability sets them apart from every other group of musicians on the planet.',
      image: 'https://lastfm.freetls.fastly.net/i/u/500x500/fa228868f27a4c51b87d28d8c3e83283.jpg',
      path: './assets/Nickelback_Burn_It_to_the_Ground.mp3',
    },
    {
      id: 4,
      song: 'Kryptonite',
      artist: '3 Doors Down',
      description: 'One of the most successful rock bands to have emerged in recent years, 3 Doors Down is considered a phenomenon within the music industry. Often called 3DD, this five-piece outfit came out of smalltown Mississippi to become a record-breaking act whose two albums and handful of singles have sold in the millions. The band became the first debut act in the history of the record charts to hit number one concurrently in Modern Rock, Active Rock, Album Rock, and Heritage Rock radio formats. ',
      image: 'https://i0.wp.com/www.songwritingmagazine.co.uk/wp-content/uploads/3-doors-down-1-by-dove-shore.jpg',
      path: './assets/3_Doors_Down_Kryptonite.mp3',
    },
    {
      id: 5,
      song: 'My Sacrifice',
      artist: 'Creed',
      description: 'Creed is a modern rock band of grassroots troubadours that performs highly inspirational music with a message, within the lines of a simple and unaffected genre called “new-era” rock. The band, led by vocalist Scott Stapp, features Mark Tremonti on guitar, Brian Marshall on bass, and Scott Phillips on drums.',
      image: 'https://i.scdn.co/image/ab67616d0000b273a32f2ae4dade83e0d7a294f4',
      path: './assets/Creed_My_Sacrifice.mp3',
    },
    {
      id: 6,
      song: 'Lifeline',
      artist: 'Papa Roach',
      description: 'Papa Roach has been described as alternative metal, hard rock, rap metal, alternative rock, nu metal, rap rock, punk rock, pop rock, and rapcore. The band also utilizes elements of pop, electronic, and hip hop. The band started as a hardcore punk band. They formed in 1993 in Vacaville, California when lead singer Jacoby Shaddix and drummer Dave Buckner met on the Vacaville High School football field during an game of football where they started talking about music.',
      image: 'https://i.iheart.com/v3/catalog/artist/7772?ops=fit(720%2C720)',
      path: './assets/Papa_Roach_Lifeline.mp3',
    },
  ],
];

export default songsData;
